


















.build/uno/arduino/hooks.o : /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/hooks.c
	@echo arduino/hooks.c
	@mkdir -p .build/uno/arduino
	@/usr/local/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=166 -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/local/share/arduino/hardware/arduino/avr/variants/standard -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino   -o $@ -c /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/hooks.c
include .build/uno/arduino/hooks.d

.build/uno/arduino/wiring_shift.o : /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/wiring_shift.c
	@echo arduino/wiring_shift.c
	@mkdir -p .build/uno/arduino
	@/usr/local/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=166 -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/local/share/arduino/hardware/arduino/avr/variants/standard -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino   -o $@ -c /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/wiring_shift.c
include .build/uno/arduino/wiring_shift.d

.build/uno/arduino/wiring_digital.o : /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/wiring_digital.c
	@echo arduino/wiring_digital.c
	@mkdir -p .build/uno/arduino
	@/usr/local/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=166 -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/local/share/arduino/hardware/arduino/avr/variants/standard -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino   -o $@ -c /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/wiring_digital.c
include .build/uno/arduino/wiring_digital.d

.build/uno/arduino/wiring_analog.o : /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/wiring_analog.c
	@echo arduino/wiring_analog.c
	@mkdir -p .build/uno/arduino
	@/usr/local/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=166 -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/local/share/arduino/hardware/arduino/avr/variants/standard -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino   -o $@ -c /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/wiring_analog.c
include .build/uno/arduino/wiring_analog.d

.build/uno/arduino/wiring.o : /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/wiring.c
	@echo arduino/wiring.c
	@mkdir -p .build/uno/arduino
	@/usr/local/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=166 -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/local/share/arduino/hardware/arduino/avr/variants/standard -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino   -o $@ -c /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/wiring.c
include .build/uno/arduino/wiring.d

.build/uno/arduino/wiring_pulse.o : /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/wiring_pulse.c
	@echo arduino/wiring_pulse.c
	@mkdir -p .build/uno/arduino
	@/usr/local/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=166 -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/local/share/arduino/hardware/arduino/avr/variants/standard -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino   -o $@ -c /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/wiring_pulse.c
include .build/uno/arduino/wiring_pulse.d

.build/uno/arduino/WInterrupts.o : /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/WInterrupts.c
	@echo arduino/WInterrupts.c
	@mkdir -p .build/uno/arduino
	@/usr/local/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=166 -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/local/share/arduino/hardware/arduino/avr/variants/standard -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino   -o $@ -c /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/WInterrupts.c
include .build/uno/arduino/WInterrupts.d






.build/uno/arduino/CDC.o : /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/CDC.cpp
	@echo arduino/CDC.cpp
	@mkdir -p .build/uno/arduino
	@/usr/local/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=166 -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/local/share/arduino/hardware/arduino/avr/variants/standard -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/CDC.cpp
include .build/uno/arduino/CDC.d

.build/uno/arduino/PluggableUSB.o : /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/PluggableUSB.cpp
	@echo arduino/PluggableUSB.cpp
	@mkdir -p .build/uno/arduino
	@/usr/local/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=166 -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/local/share/arduino/hardware/arduino/avr/variants/standard -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/PluggableUSB.cpp
include .build/uno/arduino/PluggableUSB.d

.build/uno/arduino/IPAddress.o : /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/IPAddress.cpp
	@echo arduino/IPAddress.cpp
	@mkdir -p .build/uno/arduino
	@/usr/local/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=166 -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/local/share/arduino/hardware/arduino/avr/variants/standard -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/IPAddress.cpp
include .build/uno/arduino/IPAddress.d

.build/uno/arduino/WMath.o : /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/WMath.cpp
	@echo arduino/WMath.cpp
	@mkdir -p .build/uno/arduino
	@/usr/local/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=166 -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/local/share/arduino/hardware/arduino/avr/variants/standard -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/WMath.cpp
include .build/uno/arduino/WMath.d

.build/uno/arduino/HardwareSerial3.o : /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial3.cpp
	@echo arduino/HardwareSerial3.cpp
	@mkdir -p .build/uno/arduino
	@/usr/local/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=166 -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/local/share/arduino/hardware/arduino/avr/variants/standard -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial3.cpp
include .build/uno/arduino/HardwareSerial3.d

.build/uno/arduino/Print.o : /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/Print.cpp
	@echo arduino/Print.cpp
	@mkdir -p .build/uno/arduino
	@/usr/local/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=166 -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/local/share/arduino/hardware/arduino/avr/variants/standard -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/Print.cpp
include .build/uno/arduino/Print.d

.build/uno/arduino/USBCore.o : /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/USBCore.cpp
	@echo arduino/USBCore.cpp
	@mkdir -p .build/uno/arduino
	@/usr/local/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=166 -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/local/share/arduino/hardware/arduino/avr/variants/standard -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/USBCore.cpp
include .build/uno/arduino/USBCore.d

.build/uno/arduino/new.o : /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/new.cpp
	@echo arduino/new.cpp
	@mkdir -p .build/uno/arduino
	@/usr/local/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=166 -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/local/share/arduino/hardware/arduino/avr/variants/standard -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/new.cpp
include .build/uno/arduino/new.d

.build/uno/arduino/main.o : /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/main.cpp
	@echo arduino/main.cpp
	@mkdir -p .build/uno/arduino
	@/usr/local/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=166 -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/local/share/arduino/hardware/arduino/avr/variants/standard -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/main.cpp
include .build/uno/arduino/main.d

.build/uno/arduino/Tone.o : /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/Tone.cpp
	@echo arduino/Tone.cpp
	@mkdir -p .build/uno/arduino
	@/usr/local/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=166 -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/local/share/arduino/hardware/arduino/avr/variants/standard -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/Tone.cpp
include .build/uno/arduino/Tone.d

.build/uno/arduino/HardwareSerial0.o : /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial0.cpp
	@echo arduino/HardwareSerial0.cpp
	@mkdir -p .build/uno/arduino
	@/usr/local/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=166 -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/local/share/arduino/hardware/arduino/avr/variants/standard -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial0.cpp
include .build/uno/arduino/HardwareSerial0.d

.build/uno/arduino/HardwareSerial1.o : /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial1.cpp
	@echo arduino/HardwareSerial1.cpp
	@mkdir -p .build/uno/arduino
	@/usr/local/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=166 -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/local/share/arduino/hardware/arduino/avr/variants/standard -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial1.cpp
include .build/uno/arduino/HardwareSerial1.d

.build/uno/arduino/HardwareSerial.o : /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial.cpp
	@echo arduino/HardwareSerial.cpp
	@mkdir -p .build/uno/arduino
	@/usr/local/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=166 -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/local/share/arduino/hardware/arduino/avr/variants/standard -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial.cpp
include .build/uno/arduino/HardwareSerial.d

.build/uno/arduino/Stream.o : /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/Stream.cpp
	@echo arduino/Stream.cpp
	@mkdir -p .build/uno/arduino
	@/usr/local/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=166 -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/local/share/arduino/hardware/arduino/avr/variants/standard -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/Stream.cpp
include .build/uno/arduino/Stream.d

.build/uno/arduino/abi.o : /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/abi.cpp
	@echo arduino/abi.cpp
	@mkdir -p .build/uno/arduino
	@/usr/local/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=166 -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/local/share/arduino/hardware/arduino/avr/variants/standard -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/abi.cpp
include .build/uno/arduino/abi.d

.build/uno/arduino/WString.o : /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/WString.cpp
	@echo arduino/WString.cpp
	@mkdir -p .build/uno/arduino
	@/usr/local/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=166 -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/local/share/arduino/hardware/arduino/avr/variants/standard -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/WString.cpp
include .build/uno/arduino/WString.d

.build/uno/arduino/HardwareSerial2.o : /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial2.cpp
	@echo arduino/HardwareSerial2.cpp
	@mkdir -p .build/uno/arduino
	@/usr/local/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=166 -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/local/share/arduino/hardware/arduino/avr/variants/standard -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial2.cpp
include .build/uno/arduino/HardwareSerial2.d



.build/uno/arduino/libarduino.a : .build/uno/arduino/hooks.o .build/uno/arduino/wiring_shift.o .build/uno/arduino/wiring_digital.o .build/uno/arduino/wiring_analog.o .build/uno/arduino/wiring.o .build/uno/arduino/wiring_pulse.o .build/uno/arduino/WInterrupts.o .build/uno/arduino/CDC.o .build/uno/arduino/PluggableUSB.o .build/uno/arduino/IPAddress.o .build/uno/arduino/WMath.o .build/uno/arduino/HardwareSerial3.o .build/uno/arduino/Print.o .build/uno/arduino/USBCore.o .build/uno/arduino/new.o .build/uno/arduino/main.o .build/uno/arduino/Tone.o .build/uno/arduino/HardwareSerial0.o .build/uno/arduino/HardwareSerial1.o .build/uno/arduino/HardwareSerial.o .build/uno/arduino/Stream.o .build/uno/arduino/abi.o .build/uno/arduino/WString.o .build/uno/arduino/HardwareSerial2.o
	@echo Linking libarduino.a
	@/usr/local/share/arduino/hardware/tools/avr/bin/avr-ar rcs $@ $^















.build/uno/src/sketch.o : .build/uno/src/sketch.cpp
	@echo src/sketch.cpp
	@mkdir -p .build/uno/src
	@/usr/local/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=166 -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/local/share/arduino/hardware/arduino/avr/variants/standard -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions -iquote src  -o $@ -c .build/uno/src/sketch.cpp
include .build/uno/src/sketch.d







.build/uno/firmware.elf : .build/uno/src/sketch.o .build/uno/arduino/libarduino.a
	@echo Linking firmware.elf
	@/usr/local/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega328p -Wl,-Os -Wl,--gc-sections -o $@ $^ -lm


.build/uno/firmware.hex : .build/uno/firmware.elf
	@echo Converting to firmware.hex
	@/usr/local/share/arduino/hardware/tools/avr/bin/avr-objcopy -O ihex -R .eeprom $^ $@

include .build/uno/src/dependencies.d .build/uno/arduino/dependencies.d

all : .build/uno/firmware.hex
	@true

